openapi: 3.0.1
info:
  version: 1.0.0
  title: ReCodeCamp API - Documentation
  description: API Documentation for recodecamp
  termsOfService: https://recodecamp-web.vercel.app/terms
  contact:
    name: jazicorn
    email: jazicorndev@gmail.com
    url: https://github.com/jazicorn/
  license:
    name: MIT
    url: https://github.com/jazicorn/recodecamp/LICENSE.md
servers:
  - url: https://recodecamp-api.vercel.app
    description: Production Server
components:
  schemas:
    Category:
      $ref: 'src/docs/models/category.schema.yaml'
paths:
  /:
    $ref: 'src/docs/paths/index.docs.yaml'
  /categories/js:
    $ref: 'src/docs/paths/categories/javascript.docs.yaml'
  /categories/java:
    $ref: 'src/docs/paths/categories/java.docs.yaml'
  /categories/py:
    $ref: 'src/docs/paths/categories/python.docs.yaml'
  /js/var/declare/all:
    $ref: 'src/docs/paths/langs/javascript/js-var-declare-all.docs.yaml'
  /js/var/declare/var:
    $ref: 'src/docs/paths/langs/javascript/js-var-declare-var.docs.yaml'
  /js/var/declare/const:
    $ref: 'src/docs/paths/langs/javascript/js-var-declare-const.docs.yaml'
  /js/var/declare/let:
    $ref: 'src/docs/paths/langs/javascript/js-var-declare-let.docs.yaml'
